### ISSUE TITLE
Will GPU cluster/heterogeneous cluster trace be released?

### ISSUE THREAD

**Issue by xiandong79** [alibaba/clusterdata#1]

**Comment by xiandong79** [comment]
Guys in our group are working on "heterogeneous cluster management for workloads with soft constraints" topic. Heterogeneous cluster trace would be a great help.


Thanks.

**Comment by furykerry** [comment]
We will release more data, and very probably about  heterogeneous clusters, but I'm afraid it will be not release very soon.  This is our first public released cluster data, so we may need some time to collect more feedback about the data before we release more data. 

You're welcome to give more detail about the data you desire, such as fields, scenarios.  We will consider your requests once we have some clarified plans. Stay tuned :)

BTW Google has release some data about heterogeneous clusters years ago , you may give it a try. https://github.com/google/cluster-data

**Comment by HaiyangDING** [comment]
The new trace does not container GPU info and we will see if we could be able to do so in the next version (2019). Closing the issue.
