### ISSUE TITLE
When will the GPU cluster data be available?

### ISSUE THREAD

**Issue by ccrhx4** [alibaba/clusterdata#102]
Hello,

I noticed that the GPU cluster trace schema had been merged. When will be trace data be available?

Thanks!

Huanxing

**Comment by qzweng** [comment]
Thanks for the attention! The GPU data is available now under [cluster-trace-gpu-v2020/data](https://github.com/alibaba/clusterdata/tree/master/cluster-trace-gpu-v2020/data).
