### ISSUE TITLE
Error usage of tar when extracting in 2020 trace

### ISSUE THREAD

**Issue by yzs981130** [alibaba/clusterdata#104]
In the `Usage` section of [README of Cluster trace 2020](https://github.com/alibaba/clusterdata/blob/64bb158d185a26406eaa09144aa29ced0ed88397/cluster-trace-gpu-v2020/README.md), the tar command `tar -xzf pai_*.tar.gz` seems not to work as expected.

Ref: https://stackoverflow.com/questions/16933221/shell-tar-not-found-in-archive-error-when-using-regular-expression

**Comment by qzweng** [comment]
The command has been updated as suggested. Thanks for your input!
