### ISSUE TITLE
Code for the simulator

### ISSUE THREAD

**Issue by tholop** [alibaba/clusterdata#108]
Hello,
The NSDI22 paper relies on a discrete simulator, apparently released in this repository. I am interested in the experiment scripts and the simulator, but I can't find them in the code. Please, have they been released yet?
Thank you!

P.S. Here is the section where the simulator is mentioned in the paper (Section 5.2 of https://home.cse.ust.hk/~weiwa/papers/weng-nsdi22.pdf):
![image](https://user-images.githubusercontent.com/32133147/139284217-94238de9-7a27-42da-95e6-a8c7828bf1f8.png)

**Comment by qzweng** [comment]
The code for the simulator has been released in [cluster-trace-gpu-v2020/simulator](https://github.com/alibaba/clusterdata/tree/master/cluster-trace-gpu-v2020/simulator). Thanks!
