### ISSUE TITLE
Scripts to populate MS call graphs

### ISSUE THREAD

**Issue by mtoslalibu** [alibaba/clusterdata#110]
Thanks for this amazing repo! 
Did you also have any scripts to populate MS call graphs (e.g., from traces to dags) and any other documentation? It is a bit different from distributed traces we usually in Jaeger or so.

**Comment by niewuya** [comment]
Thanks for your interest. I kindly recommend that you should read the introduction of the MS_CallGraph_Table. There are two key metrics, traceid and rpcid. Each call graph has a unique traceid. And rpcid records the call dependencies, which could be used to form a call graph. 

Actually, we fetch and analyze the call graph via MaxCompute, a big data framework in Alibaba. In the future, I will release a simple script to do that.
