### ISSUE TITLE
Infomation about recurring jobs in cluster-trace-gpu-v2020

### ISSUE THREAD

**Issue by ChAnYaNG97** [alibaba/clusterdata#114]
In section 5.2 of the paper, 65% of jobs are recurring jobs submmited at least 5 times by same users. But in clusterdata, jobs have unique ids, thus recurrence information of jobs can not be attained. I wonder if the recurrence information can be added to the dataset.

**Comment by karlhjm** [comment]
你好！我已经收到你的邮件！

**Comment by qzweng** [comment]
Thanks for your interest @ChAnYaNG97. Jobs' recurrence information are revealed in `group` tag -- job instances with the same `group` id are treated as recurring ones. See [pai_group_tag_table](https://github.com/alibaba/clusterdata/tree/master/cluster-trace-gpu-v2020#pai_group_tag_table) for detailed description.

**Comment by ChAnYaNG97** [comment]
Thanks a lot!@qzweng
