### ISSUE TITLE
extract critical path from microservice trace

### ISSUE THREAD

**Issue by Romero027** [alibaba/clusterdata#118]
is there a way to extract the critical path from the microservice trace? Thanks

**Comment by niewuya** [comment]
A critical path is the longest path in a call graph. I recommend you build call graphs and extract the critical path for each call graph. To do so, you could conduct tree traversal on each depth gradually. On each depth, you could judge the parallel or sequential calls first. For parallel calls, the calls with the largest RT belong to the critical path, while all sequential calls belong to the critical path.

**Comment by Romero027** [comment]
Thanks for the suggestion!
