### ISSUE TITLE
[cluster-trace-gpu-v2020]: What's the meaning of "cpu_usage", "gpu_wrk_util" in "pai_sensor_table" and "machine_cpu_usr", "machine_cpu_kernel" in "pai_machine_metric"?

### ISSUE THREAD

**Issue by Jackjiayou** [alibaba/clusterdata#125]
请问pai_sensor_table  表cpu_usage与gpu_wrk_util  是相对于什么资源的百分比，是与worker_name所在的机器比较还是与pai_task_table中plan_cpu和plan_gpu比较，还是与运行这个task的机器所生成的虚拟环境的资源比较？
    另外pai_machine_metric表中machine_cpu_kernel与machine_cpu_usr与machine_cpu  之间是什么关系呀？还有machine_num_worker这个字段是表示什么意思？  
麻烦解答一下 非常感谢.
![image](https://user-images.githubusercontent.com/43378246/156094464-b42ac68c-1f53-4442-8d1c-c0d72288bd12.png)
![image](https://user-images.githubusercontent.com/43378246/156094547-9ea89efc-121e-46a6-9092-8adb0edb0e11.png)

**Comment by qzweng** [comment]
Hi @Jackjiayou,

- `cpu_usage` and `gpu_wrk_util` are **absolute values**. Say, `cpu_usage=600` means the instance uses 6 vCPU cores and `gpu_wrk_util=50` means it uses 50% of a GPU's computing power (see `Utilization->GPU` in [Example `nvidia-smi` output](https://developer.nvidia.com/nvidia-system-management-interface)).

- `machine_cpu` ~= `machine_cpu_usr` + `machine_cpu_kernel` + `machine_cpu_iowait`; please refer to [iostat - Linux man page](https://linux.die.net/man/1/iostat) for further details.

- `machine_num_worker` represents the number of instances running on that machine, averaged over all time. One entry of pai_sensor_table gives 1 count to the `machine_num_worker` of its host `machine`.

**Comment by Jackjiayou** [comment]
> Hi @Jackjiayou,
> 
> * `cpu_usage` and `gpu_wrk_util` are **absolute values**. Say, `cpu_usage=600` means the instance uses 6 vCPU cores and `gpu_wrk_util=50` means it uses 50% of a GPU's computing power (see `Utilization->GPU` in [Example `nvidia-smi` output](https://developer.nvidia.com/nvidia-system-management-interface)).
> * `machine_cpu` ~= `machine_cpu_usr` + `machine_cpu_kernel` + `machine_cpu_iowait`; please refer to [iostat - Linux man page](https://linux.die.net/man/1/iostat) for further details.
> * `machine_num_worker` represents the number of instances running on that machine, averaged over all time. One entry of pai_sensor_table gives 1 count to the `machine_num_worker` of its host `machine`.

Hi @qzweng, 
Hope you're having a good day. Thank you very much for your help, I appreciate it. And I have a few more questions below.
- And  what's the connection between pai_sensor_table 's cpu_usage  and  pai_machine_metric's machine_cpu? The same question on gpu_wrk_util and  machine_gpu .   
- What's the unit of machine_cpu and machine_gpu of pai_machine_metric ? 
- What's the connection between  machine_gpu of pai_machine_metric and cap_gpu of pai_machine_spec? 
- Is the machine_num_worker is mean that number of instances running on that machine(averaged over all time) in the same time?
Thanks

**Comment by qzweng** [comment]
> And what's the connection between pai_sensor_table 's cpu_usage and pai_machine_metric's machine_cpu? The same question on gpu_wrk_util and machine_gpu .

Metrics in `pai_sensor_table` are derived by taking the average of all data in the instance's lifetime. Metrics in `pai_machine_metric` show the host machine's resource utilization (averaged by the instance's lifetime).

For example, if one node, having 20 vCPUs, has 2 instances running on it; each instance constantly uses 5 vCPUs. The cpu_usage of each instance in pai_sensor_table would be 500 while the node's machine_cpu would be 50 (10 vCPUs out of 20 vCPUs are used).

The similar relationship lies between gpu_wrk_util and machine_gpu.

> What's the unit of machine_cpu and machine_gpu of pai_machine_metric ?

`machine_cpu`: percentage of machine CPU capacity. range: 0-100.
`machine_gpu`: percentage of machine GPU utilization. range: 0-800 (at most 8 GPUs on one machine).

> What's the connection between machine_gpu of pai_machine_metric and cap_gpu of pai_machine_spec?

`machine_gpu`: as explained above.
`cap_gpu`: GPU capacity; number of GPU in the machine.

> The meaning of machine_num_worker is number of instances running on that machine(averaged over all time) in the same time,right?

Averaged over all time the instance's running time. The former comment in this issue has been revised.

> What's the mean of machine_cpu_usr and machine_cpu_kernel ?

`machine_cpu_usr`:  “%user. Show the percentage of CPU utilization that occurred while executing at the user level (application).” [ref]
`machine_cpu_kernel`: "%system. Show the percentage of CPU utilization that occurred while executing at the system level (kernel)." [ref]

[ref]: iostat(1) - Linux man page, https://linux.die.net/man/1/iostat

**Comment by Jackjiayou** [comment]
Thanks a lot!@qzweng
