### ISSUE TITLE
What's the meaning of machine_cpu_usr and machine_cpu_kernel   ?

### ISSUE THREAD

**Issue by Jackjiayou** [alibaba/clusterdata#126]
About cluster-trace-gpu-v2020.
-What's the connection between pai_sensor_table 's cpu_usage and pai_machine_metric's machine_cpu? The same question on gpu_wrk_util and machine_gpu .
- What's the unit of machine_cpu and machine_gpu of pai_machine_metric ?
- What's the connection between machine_gpu of pai_machine_metric and cap_gpu of pai_machine_spec?
- The meaning of machine_num_worker is number of instances running on that machine(averaged over all time) in the same time,right?
- What's the mean of machine_cpu_usr and machine_cpu_kernel ?

**Comment by qzweng** [comment]
Duplicated in #125. Closed.
