### ISSUE TITLE
Clarification of the task info

### ISSUE THREAD

**Issue by kzhang28** [alibaba/clusterdata#129]
Could you clarify the meaning of some item in the task table:
In the task table, what does the "plan_gpu" exactly mean?  Is it the **total** gpu requested by all the instances within the task, or it is the gpu request by a **single instance** of the task? 
Thank you!

**Comment by qzweng** [comment]
Hi @kzhang28,

`plan_cpu`, `plan_gpu` and `plan_mem` mean the resource requested by each **single instance**. For example, a task with `inst_num=4` and `plan_gpu=100` would request 4 GPUs in total.

Thank you for pointing this out!

**Comment by Jackjiayou** [comment]
> Hi @kzhang28,
> 
> `plan_cpu`, `plan_gpu` and `plan_mem` mean the resource requested by each **single instance**. For example, a task with `inst_num=4` and `plan_gpu=100` would request 4 GPUs in total.
> 
> Thank you for pointing this out!

Hi  @qzweng  请问是inst_num=4 代表申请4个GPU吗，plan_gpu  = 100 ,代表申请这四个gpu的百分百资源吗
