### ISSUE TITLE
2021微服务数据集有每次请求的数据长度的数据吗？

### ISSUE THREAD

**Issue by ZacharyJia** [alibaba/clusterdata#130]

**Comment by niewuya** [comment]
请求的数据是指传参吗？请求的传参暂时不公开。谢谢关注！

**Comment by GitHubDiom** [comment]
你好，我估计原issue是指请求参数的长度，而不是具体的数据。
我想请问具体到每个微服务的输入输出参数可以加密之后公开吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: niewuya ***@***.***&gt;
发送时间: 2022年3月27日 19:58
收件人: alibaba/clusterdata ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [alibaba/clusterdata] 2021微服务数据集有每次请求的数据长度的数据吗？ (Issue #130)






请求的数据是指传参吗？请求的传参暂时不公开。谢谢关注！

**Comment by ZacharyJia** [comment]
> 请求的数据是指传参吗？请求的传参暂时不公开。谢谢关注！

是指请求和返回数据的 数据长度。 谢谢！

**Comment by niewuya** [comment]
你好，请求和返回数据的数据长度 还有没公开的计划。谢谢！

**Comment by ZacharyJia** [comment]
> 你好，请求和返回数据的数据长度 还有没公开的计划。谢谢！

好的谢谢
