### ISSUE TITLE
MS_CallGraph_Table Timestamps

### ISSUE THREAD

**Issue by gwinch97** [alibaba/clusterdata#147]
Hi,

Firstly, thank you very much for releasing such a valuable dataset.

I had a few questions regarding the timestamp values in MS_CallGraph_Table:

1) Are these call graphs sampled from the same provided 12-hour window as the other metrics, or are they sampled across the whole 7 day dataset?

2) What exactly is the unit of measurement for this timestamp value (minutes,seconds,milliseconds)? I can't seem to understand why the maximum timestamp across all calls is 10499999.0, if this was milliseconds it would correspond to day 2.9, which is neither the 12hr window nor the 7 day larger dataset.

Many thanks for any help you can give.

**Comment by danibachar** [comment]
I wonder if this answers your question - https://github.com/alibaba/clusterdata/issues/144

**Comment by karlhjm** [comment]
你好，邮件已收到。我处理完会马上给你回复，祝生活愉快！

**Comment by gwinch97** [comment]
> I wonder if this answers your question - [#144 ](https://github.com/alibaba/clusterdata/issues/144)

Many thanks for highlighting, it answers my first question (if that person is correct in their assumptions).

Although I am still confused about the timestamps associated with the call graphs, why would the largest timestamp be 10499999.0 (I'm assuming milliseconds), which is day 2.9, if they were a 0.5% sample of the 10 billion call graphs across the whole 7 days.

**Comment by gwinch97** [comment]
Apologies, I did not mean to mark this as completed.

**Comment by danibachar** [comment]
> > I wonder if this answers your question - [#144 ](https://github.com/alibaba/clusterdata/issues/144)
> 
> Many thanks for highlighting, it answers my first question (if that person is correct in their assumptions).
> 
> Although I am still confused about the timestamps associated with the call graphs, why would the largest timestamp be 10499999.0 (I'm assuming milliseconds), which is day 2.9, if they were a 0.5% sample of the 10 billion call graphs across the whole 7 days.

But why assume - it clearly says that it is
`timestamp: Timestamp of recorded metrics. Range from 0 to 43_200_000 for twelve hours (12 * 60 * 60 * 1000). The recording interval is the 30s (30 * 1000).`

As far as I'm concerned `43_200_000 > 10_499_999.0`

I think your calculation is wrong (which I assume you do 10_499_999.0 / (1000*60*60) ~= 2.9
You forgot to divide it also by 12 ((12 * 60 * 60 * 1000)) and align to the interval

**Comment by gwinch97** [comment]
> But why assume - it clearly says that it is
timestamp: Timestamp of recorded metrics. Range from 0 to 43_200_000 for twelve hours (12 * 60 * 60 * 1000). The recording interval is the 30s (30 * 1000).

I only said assumed because this was the description of metric timestamps and not the call graph table, although I was needlessly tentative.

You're right that I messed up the calculation. But I don't understand why you would divide by 12 here, the calculation should be (24 * 60 * 60) to convert from milliseconds to days. Indeed the maximum timestamp on the call graph table is 2.9hrs, which is less than the 12hrs sampled for the metrics. 

My question is whether these calls were sampled within the same time period as the metrics.

**Comment by niewuya** [comment]
Thanks for your interest. These call graphs were sampled within the same time period as the metrics. We prepare to release a new version of microservices traces, which contains diverse metrics in a long time window.

**Comment by gwinch97** [comment]
Many thanks for your response.

As the calls only seem to be sampled in a 2.9hr window, compared to the 12hr window of the metrics. Would it be possible to align the calls with the metrics?

**Comment by gwinch97** [comment]
Sorry for the late response.

But in regards to the timestamp of call graphs. If the maximum timestamp in the MS_CallGraph_Table is 10499999ms, which is 10499999/(1000*60*60) = 2.9 hours, does this simply mean that the latest a call was measured in this dataset was simply 2.9hrs and there were no calls recorded for the latter 9.1hrs in the 12hr trace?

Sorry for so many questions, but I am very interested in exploring this dataset, and lookfoward greatly to the microservices-trace-v2022. Thank you again for this opportunity!

**Comment by gwinch97** [comment]
Nevermind, I think I've found the issue. The cURL download failed before I downloaded all MSCallGraph tar files, therefore I did not have the complete dataset. Apologies for the waste of time, I look forward to exploring the new dataset!

**Comment by Cloud-and-Distributed-Systems** [comment]
That is fine. Thanks for your interest.
