### ISSUE TITLE
PAI dataset: CPU usage greater than CPU requested

### ISSUE THREAD

**Issue by vikcas** [alibaba/clusterdata#151]
Hi, 
First, I'd like you to thank you for sharing the PAI dataset.

I have recently started to look at it, and I've found that in some cases the CPU usage is above the CPU planned, as can be seen in the figure below.
![image](https://user-images.githubusercontent.com/10379583/188642283-dcb41399-6a5f-45ed-9bd6-e7429ae0ce39.png)

I have been looking for an answer, but I only found this issue #11, but I'm not sure if this holds for the PAI dataset.
Also, reading your article (_MLaaS in the Wild: Workload Analysis and Scheduling in Large-Scale Heterogeneous GPU Clusters_), figures 20-21, I've seen that the CPU usage should be below than the CPU planned.
Is there any other reason for this behavior? 

Thank you.

**Comment by qzweng** [comment]
Hi Victor,

Thanks for the interest! To clarify, I inferred that the `examples_sampled` in the plot is a DataFrame merged by "pai_task_table" and "pai_sensor_table", where each data point represents the CPU usage and CPU planned of **one worker instance of a task**.

In fact, in PAI, instances of a task can use more resources than requested, as long as there are spare resources in the host machines. As shown in Figure 5d of the "MLaaS in the Wild" paper (the last paragraph above Sec. 4), the "CPU usage being above the CPU planned", or CPU overuse, is more common than GPU or Memory overuse: "There are 19% task instances overusing CPUs while 3% (9%) instances use more GPUs (memory) than they requested."

Best,
Qizhen

**Comment by vikcas** [comment]
Hi Qizhen, 

Thank you for your answer. I've keep working with the dataset, but I'm not able to fully understand how to interpret some of the values.
From the documentation, I understand that a user submit a job, which can be identified by _job_name_, then a job can have several tasks identified by _task_name_. Up to here, there is no issue.
Then, each task has several instances, that can be identified through _inst_name_ or _inst_id_, is there any logical difference between this two identifiers? I've seen that their values are different. 
Next, there is _inst_num_ that describes the number of instances launched by a single task, so from the documentation I'm assuming that _inst_name_ or _inst_id_ are the same, and then I can use _inst_num_ to know how many of them are actually running.
Further, there is _worker_name_, which from the description, is able to distinguish instances. So my intuition is that there should be as many _worker_name_ as _inst_num_.
However, given the data I'm not able to see this relations on it. Let's see one example:
![alibaba_sample_data](https://user-images.githubusercontent.com/10379583/190194531-8ce1bfcb-ed60-4791-8ee2-71791c579414.png)

For instance, in the first line, it can be seen that there is one _worker_name_ but 2 instances of it, despite the _inst_num_ value is 1. So, could you please help me understanding the meaning of these identifiers? 
My goal is to relate the _cpu_usage_ with the reserved resources (_plan_cpu_), but given these differences I'm not sure how can I relate these values. Could you give me a hint or an example on how I can do that? 
For example taking the first row of the presented table, should be multiply the _plan_cpu_ by the _inst_num_ and then compared with the _cpu_usage_ of each _worker_name_?

Thank you very much for your time and consideration.

**Comment by qzweng** [comment]
- `inst_id` is more like `job_id`---each `job_name` is correlated with one `inst_id`. Therefore, one `inst_id` can have multiple workers with different `worker_name`.
- Each worker (or instance) can be identified by `worker_name` (or `inst_name`). Though "worker" and "instance" are exchangeable, `worker_name` is more preferred.
