### ISSUE TITLE
Overall cluster utilisation ( in terms of CPU or GPU) 

### ISSUE THREAD

**Issue by LalchandPandia** [alibaba/clusterdata#163]
Did you observe any benefit in overall cluster utilization ( in terms of CPU or GPU) either due to better prediction of recurring tasks' runtime or due to GPU sharing?

**Comment by qzweng** [comment]
Both GPU sharing and duration-prediction-based scheduling can achieve similar workload performance with fewer GPUs, therefore, the cluster utilization can be improved. Please refer to Fig. 8 and Fig. 13 in the MLaaS (NSDI ’22) paper for more details: https://www.usenix.org/conference/nsdi22/presentation/weng

Thank you for the question.

**Comment by LalchandPandia** [comment]
Fig 13 , shows improvement in average JCT. Does duration-prediction-based scheduling  also led to better GPU utilization?

**Comment by LalchandPandia** [comment]
I mean is there a cluster wide benefit?
