### ISSUE TITLE
Changing of curl scripts to wget to download data of micro services 2021

### ISSUE THREAD

**Issue by S1LV3RJ1NX** [alibaba/clusterdata#178]
The [fetchdata.sh](https://github.com/alibaba/clusterdata/blob/master/cluster-trace-microservices-v2021/fetchData.sh) script uses curl to download the dataset; the connection breaks if even if you have a fast internet connection. Hence I chnaged the curl scripts to wget scripts. If anyone needs can use the following commands instead:

**Node_Table:**
```wget -c --retry-connrefused --tries=0 --timeout=50 http://alitrip.oss-cn-zhangjiakou.aliyuncs.com/TraceData/node/Node.tar.gz```

**MS_Metrics_Table:**
```for i in {0..11}; do wget -c --retry-connrefused --tries=0 --timeout=50 http://alitrip.oss-cn-zhangjiakou.aliyuncs.com/TraceData/MSResource/MSResource_${i}.tar.gz; done```

** MS_MCR_RT_Table:**
```for i in {0..24}; do wget -c --retry-connrefused --tries=0 --timeout=50 http://alitrip.oss-cn-zhangjiakou.aliyuncs.com/TraceData/MSRTQps/MSRTQps_${i}.tar.gz; done```

** MS_CallGraph_Table:**
```for i in {0..144}; do wget -c --retry-connrefused --tries=0 --timeout=50 http://alitrip.oss-cn-zhangjiakou.aliyuncs.com/TraceData/MSCallGraph/MSCallGraph_${i}.tar.gz; done```

**Comment by S1LV3RJ1NX** [comment]
Closing this issue.

**Comment by niewuya** [comment]
Thank you for your contribution. It is very helpful. We will update it later.
