### ISSUE TITLE
Question about sigma.png

### ISSUE THREAD

**Issue by lioncruise** [alibaba/clusterdata#18]
Hello guys, can anyone give a description of the architecture diagram below? I wonder whether the scheduling of the 1.3k-machine cluster is done by two separated schedulers sigmaMaster and FuxiMaster, while sigmaMaster responses for containerized online service instances and FuxiMaster responses for traditional batch jobs. Two schedulers have their own restrictions and allocations rules on the cluster resources respectively and do not affect each other. I'm not quite sure about my guess, very grateful if someone could resolve my doubt.

![image](https://user-images.githubusercontent.com/12690984/34520590-3f7d1d3c-f0c4-11e7-830f-ba9ad17dac65.png)

**Comment by gaocegege** [comment]
Fuxi has a paper: http://www.vldb.org/pvldb/vol7/p1393-zhang.pdf and it may help you to understand what it is. As for sigma, http://www.infoq.com/cn/news/2017/12/Cloud-Sigma-Pouch-Alibaba is clear, IMO. It is Kubernetes-compatible so I think it is similar to Kubernetes.

**Comment by lioncruise** [comment]
Thank you very much! @gaocegege

**Comment by HaiyangDING** [comment]
Closing the issue and I will add the link of Fuxi paper to our doc. Thanks.
