### ISSUE TITLE
cluster-trace-gpu-v2020中pai_sensor_table 中cpu_usage， gpu_wrk_util，  avg_gpu_wrk_mem ， max_gpu_wrk_mem 疑问

### ISSUE THREAD

**Issue by Jackjiayou** [alibaba/clusterdata#182]
请问pai_sensor_table 中cpu_usage， gpu_wrk_util，  avg_gpu_wrk_mem ， max_gpu_wrk_mem代表一个任务（以worker_name区分）所用资源还是在这个任务执行的同时还会有别的任务一起使用cpu或者gpu从而代表着这个执行任务那一时刻这台机器所被占用的资源（包含其他任务）

**Comment by qzweng** [comment]
data `cpu_usage`, `gpu_wrk_util`, `avg_gpu_wrk_mem`, `max_gpu_wrk_mem` in `pai_sensor_table` is the metric for each instance, not the machine.

**Comment by BhAem** [comment]
What does it mean if the gpu_wrk_util is greater than 100%?
