### ISSUE TITLE
cluster-trace-gpu-v2020  论文5.2 Predictable Duration for Recurring Tasks章节中使用cart 模型预测时间是什么时间

### ISSUE THREAD

**Issue by Jackjiayou** [alibaba/clusterdata#183]
请问关于cluster-trace-gpu-v2020  论文5.2 Predictable Duration for Recurring Tasks章节中使用cart 模型预测的任务执行时间是指pai_task_table中数据的时间还是pai_instance_table中的执行时间

**Comment by qzweng** [comment]
Sec. 5.2  Predictable Duration for Recurring Tasks
> we find that most tasks are recurring, and their instance run-times can be well predicted from past executions.

> we predict the task’s average instances duration using the CART

CART predicts the runtime of `pai_instance_table`.

**Comment by Jackjiayou** [comment]
> > we find that most tasks are recurring, and their instance run-times can be well predicted from past executions.
> 
> > we predict the task’s average instances duration using the CART

Thanks
