### ISSUE TITLE
请问pai_job_duration_estimate_100K.csv 的列中有表示论文5.2中预测的时间吗

### ISSUE THREAD

**Issue by Jackjiayou** [alibaba/clusterdata#184]
请问pai_job_duration_estimate_100K.csv 的列中有表示论文5.2中预测的时间吗

**Comment by qzweng** [comment]
Yes, the last three columns in the file [pai_job_duration_estimate_100K.csv](https://github.com/alibaba/clusterdata/blob/master/cluster-trace-gpu-v2020/simulator/traces/pai/pai_job_duration_estimate_100K.csv) represents
- `user_dur`: Predicted runtime using <User> feature
- `group_dur`: Predicted runtime using <Group, User> features
- `group_gpu_dur`: Predicted runtime using <Group, User, GPU> features in Fig. 12

Besides, the performance of the scheduler that leverages corresponding prediction are shown in the Fig. 13.
