### ISSUE TITLE
请问PAI数据中task 或者instance的执行有先后顺序吗，task或者instance之间是否有依赖关系？

### ISSUE THREAD

**Issue by Jackjiayou** [alibaba/clusterdata#192]
请问PAI数据中task 或者instance的执行有先后顺序吗，是否能构造出DAG结构的关系图？是否是某个task或instance依赖于另一个task或者instance。如果有这种依赖关系的话，要怎么找出这种依赖关系。

**Comment by qzweng** [comment]
Instances are triggered by the corresponding tasks, please refer to the `task_name` col in the tables.

The dependencies among different tasks are not included in this dataset.

**Comment by Jackjiayou** [comment]
> Instances are triggered by the corresponding tasks, please refer to the `task_name` col in the tables.
> 
> The dependencies among different tasks are not included in this dataset.

谢谢   请问一个task下的多个instance之间是否有执行先后顺序，比如一个instance必须等别的instance执行完毕才能执行
