### ISSUE TITLE
The schema for online service is missed.

### ISSUE THREAD

**Issue by uchuhimo** [alibaba/clusterdata#2]
Service instance event/usage tables mentioned in [trace_201708.md](https://github.com/alibaba/clusterdata/blob/master/trace_201708.md#online-service) cannot be found in [schema.csv](https://github.com/alibaba/clusterdata/blob/master/schema.csv).

**Comment by furykerry** [comment]
Service instance event/usage tables is called container_event.csv and container_usage.csv. I've update the table names in trace_201708.md. Thans for your feedback
