### ISSUE TITLE
Add paper about the trace in README

### ISSUE THREAD

**Issue by gaocegege** [alibaba/clusterdata#20]
I found a paper [Imbalance in the Cloud: an Analysis on Alibaba Cluster Trace](http://cloud.siat.ac.cn/%7Eye/Imbalance_Ye_2017.pdf) (BIGDATA'17).

And I think we could add the link to the paper in README.

**Comment by HaiyangDING** [comment]
Thank you @gaocegege 

I have updated the doc to include this paper.

**Comment by gaocegege** [comment]
SGTM, Hope my paper will be in the doc, in the future :smile: 

I am closing the issue.
