### ISSUE TITLE
Excessive Number of HTTP Interfaces in MSCallgraph for Certain Microservices

### ISSUE THREAD

**Issue by dufanrong** [alibaba/clusterdata#201]
While analyzing the MSCallgraph in cluster-trace-microservices-v2022, I've observed an unusually high number of HTTP interfaces for specific microservices, such as MS_31900. The count goes up to tens of thousands. Upon further investigation, I noticed that this phenomenon is limited to interfaces of type HTTP.

| timestamp   | traceid         | service      | rpc_id       | rpctype | um     | uminstanceid     | interface     | dm      | dminstanceid    | rt  |
|-------------|-----------------|--------------|--------------|---------|--------|------------------|---------------|---------|-----------------|-----|
| 666799790   | T_10572747201   | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_94 | YiSTYTipcG    | MS_31900 | MS_31900_POD_7  | 1.0 |
| 666791503   | T_10572545896   | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_261| vC8inwuMdi   | MS_31900 | MS_31900_POD_17 | 0.0 |
| 666756726   | T_8055188207    | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_121| RlE4Pp_ARK   | MS_31900 | MS_31900_POD_27 | 0.0 |
| 666794385   | T_24814568720   | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_267| GSF0mJiohI   | MS_31900 | MS_31900_POD_14 | 0.0 |
| 666898773   | T_8757450109    | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_94 | n3nUmaP9BK   | MS_31900 | MS_31900_POD_9  | 1.0 |
| 666854154   | T_10574242754   | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_7  | 6YFZ5JWAmA   | MS_31900 | MS_31900_POD_13 | 1.0 |
| 666737861   | T_14369578268   | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_94 | lXK57owq2Y   | MS_31900 | MS_31900_POD_16 | 0.0 |
| 666770254   | T_23542778248   | S_10694245   | 0.1.1        | http    | MS_68938 | MS_68938_POD_261| hYk8H05n1F   | MS_31900 | MS_31900_POD_33 | 1.0 |
| 666741974   | T_10147839047   | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_59 | Id1Y2qlf4L   | MS_31900 | MS_31900_POD_17 | 0.0 |
| 666846054   | T_13888771459   | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_37 | IMl0nT51Fv   | MS_31900 | MS_31900_POD_12 | 0.0 |
| 666880932   | T_13890466572   | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_196| Hkb641m7S6   | MS_31900 | MS_31900_POD_4  | 2.0 |
| 666848797   | T_23794821828   | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_196| jYG4oEF7fj   | MS_31900 | MS_31900_POD_3  | 1.0 |
| 666897101   | T_11914288919   | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_3  | 8REByX_Irw   | MS_31900 | MS_31900_POD_31 | 0.0 |
| 666800327   | T_11910715102   | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_177| _c8x9zOuP2   | MS_31900 | MS_31900_POD_6  | 0.0 |
| 666751302   | T_13207264320   | S_10694245   | 0.1.1.1      | http    | MS_68938 | MS_68938_POD_83 | o_9Q6QDWIz   | MS_31900 | MS_31900_POD_33 | 1.0 |
| 666871574   | T_13207160148   | S_10694245   | 0.1.1        | http    | MS_68938 | MS_68938_POD_169| ZkyKcGcJxD   | MS_31900 | MS_31900_POD_26 | 0.0 |

In my understanding, each microservice should have a relatively small number of interfaces, rather than several thousand. I am curious to understand why there is such a significant proliferation of HTTP interfaces.

**Comment by niewuya** [comment]
Thank you for your question. In this scenario, the interface for the HTTP service is related to its arguments, which may result in a single HTTP service having a large number of interfaces, especially when there are multiple arguments.

**Comment by dufanrong** [comment]
I understand, thank you for your response！

**Comment by dufanrong** [comment]
I understand, thank you for your response！
