### ISSUE TITLE
For the dm and um in MSCallGraph, can not find their corresponding msname in MSResource in cluster-trace-microservices-v2021

### ISSUE THREAD

**Issue by THUzxj** [alibaba/clusterdata#202]
Thank you for your efforts in releasing this data!

I encountered this problem when joining the tables. For the dm and um in MSCallGraph, can not find their corresponding `msname` in MSResource in cluster-trace-microservices-v2021. However, the README says that in MS_Metrics_Table, the `msname` is "The name of MS, to be joined with MSName in MS_MCR_RT_Table, and DM and UM in MS_CallGraph_Table. MSName only contains stateless services, as stateful services run in other dedicated clusters."

Thus I wonder whether the um and dm fields in MSCallGraph are the names of microservices.

How to reproduce it:

```bash
$ head -n2 MSCallGraph/MSCallGraph_0.csv 
,traceid,timestamp,rpcid,um,rpctype,dm,interface,rt
0,0b133c1915919238193454000e5d37,219678,0.1.3.1.1.1.12,5cca70246befb1f4c9546d2912b9419dee54439218efa55a7a2e0e26e86ad749,mc,b1dbd3a649a3cc790fa12573c9c1aa00988e07a8818a2214208b9697238c1b11,,0
$ cat MSResource/*.csv | grep 5cca70246befb1f4c9546d2912b9419dee54439218efa55a7a2e0e26e86ad749
# no output, but it is expected to show the lines with msname = '5cca...'
```

**Comment by niewuya** [comment]
Thank you for your question and interest. MSResource only involves the microservices in two clusters, as mentioned in the README, while MS_CallGraph_Table contains the microservices in more than two clusters. Therefore, it happens that some microservices only appear in MS_CallGraph_Table.

**Comment by THUzxj** [comment]
Thank you for your quick answer! I have confirmed that there are traces in MSCallGraph whose um or dm appears in MSResource.
