### ISSUE TITLE
On preparing new version of data.

### ISSUE THREAD

**Issue by HaiyangDING** [alibaba/clusterdata#21]
The purpose of this is issue is to collect & discuss about "what to include" in the next version of releasing data.

As stated before, we have plans about releasing a version of data to fulfill the need from both academic and industry fields.

Currently we have heard of the following suggestions / requirements:

* DAG info: https://github.com/alibaba/clusterdata/issues/3
* GPU and/or heterogeneous cluster data: https://github.com/alibaba/clusterdata/issues/1

Please feel free to post your ideas here on what kind of information should be included in the next version of data, and we will evaluate these ideas and try to fulfill them depending the difficulty of collecting related information.

We are looking forward to hearing more from the community.

@gaocegege , @lioncruise , @uchuhimo , @CoffeeCandy , @xiandong79 , @lastweek, @allenbunny

**Comment by gaocegege** [comment]
@HaiyangDING 

Many thanks to Alibaba for the trace. Actually, I focus on running multiple workloads(including ML workload) in a single cluster, so I am interested in GPU.

AFAIK, there is no data trace that includes GPU usage or status, so I am not sure which info should be included, but I have one specific concern: the temperature.

Temperature is important for GPUs since it may affect the performance of GPU, so I am wondering if we could add the info into the trace.

**Comment by 412428728** [comment]
hi, thanks for alibaba's cluster data trace. In the new version data, I wonder if there can be some info about priority of online container or batch task, with which we may be able to implement more dimensional constrained scheduling algorithms. BTW, I will be grateful if the details of the expansion and reduction of an instance of an on-line service container can be exposed.

**Comment by HaiyangDING** [comment]
Just move some suggestions from other issues:

https://github.com/alibaba/clusterdata/issues/23
Would it be possible to add a field broadly classifying the root cause of the different failures? Both task failures and instance failures.
_from @Theophilusbenson_ 

https://github.com/alibaba/clusterdata/issues/24
The current data set includes CPU, mem, and disk, would it be possible to add network information?
The NIC speeds and the network utilization?  
_from @Theophilusbenson_

https://github.com/alibaba/clusterdata/issues/25
I am wondering if machine attributes such as resource capacity and information (num of cores, num of disks, num of CPUs, kernel version, clock speed, eth_speed, architecuture etc. ) can be provided? Google tracelog included the similar descriptions and it is quite important when invesitigating the compaction effectiveness and scheduling quality. Many thanks. 
_from @yangrenyu_

**Comment by CoffeeCandy** [comment]
i am wondering if the period of new version data can be longer ,may be one month,12 or 24 hours is too short to make some prediction

**Comment by HaiyangDING** [comment]
> i am wondering if the period of new version data can be longer ,may be one month,12 or 24 hours is too short to make some prediction

@CoffeeCandy Yes, we will release the data of longer duration.

**Comment by gaocegege** [comment]
Hi, is there any update? I am really excited for the next release.

**Comment by maniaabdi** [comment]
Hi. Thanks for your workload. Is there any update on tgto DAG information? #issue3
