### ISSUE TITLE
Cpu numbers

### ISSUE THREAD

**Issue by Pia-Narmadha** [alibaba/clusterdata#28]
in batch instance table 9th column is "real_cpu_max: maximum cpu numbers of actual instance running" 

most of the values in this column are less than 1 it was also mention that cpu is not normalized. can anyone explain the reason for it?

**Comment by HaiyangDING** [comment]
@Pia-Narmadha 

In 'batch_instance.csv', I found 8673603 records with 'real_cpu_max' larger than 1, which takes up ~54% of total records. To this end, I think it is a reasonable number.

Maybe I misunderstand your question?

**Comment by Pia-Narmadha** [comment]
Some tasks in the batch_task table has a plan cpu in decimal.
can you explain what does the plan cpu of 0.5 mean in the batch_task table?

**Comment by HaiyangDING** [comment]
It means that we estimate that each instance of the task would use 0.5 cpu. It is only a reference for us to decide where to put an instance of this batch task (and it is not accurate). As you know, the actual cpu used per instance is recorded in batch_instance and does not equal to the plan cpu.

**Comment by Pia-Narmadha** [comment]
Does this mean that the scheduler doesn't allocate the entire cpu for a task?

Do tasks share cpu?

Do batch jobs run on cpu allocated for service jobs?

Can you suggest an way to allocate resources to a task if we simulate the scheduler?

**Comment by HaiyangDING** [comment]
Does this mean that the scheduler doesn't allocate the entire cpu for a task?

For batch, no

Do tasks share cpu?

Yes

Do batch jobs run on cpu allocated for service jobs?

Tasks (jobs) have several priorities. For the tasks that have low priority, they can run on cpus that are allocated for service jobs, at a risk of being preempted whenever service jobs need the resource. The mechanism behind cannot be described with a few words but many works are using similar idea.

Can you suggest an way to allocate resources to a task if we simulate the scheduler?

Well, I am not sure if I could help on this one. In fact, you can make any assumption about the priority of tasks as long as it helps with your goal of the design. We could have further discussion on this if you have more specific need. Just send me email and we could also have a call about this.

**Comment by HaiyangDING** [comment]
Closing the issue.
