### ISSUE TITLE
Negative timestamps in batch_instance.csv

### ISSUE THREAD

**Issue by jcarreira** [alibaba/clusterdata#29]
It seems there are records with negative timestamps (both start and end) in the batch_instance.csv.

For instance:

> -792,-788,6850,40552,546,Terminated,1,1,2,0.58,,

I didn't see any mention of this in the documentation (only about timestamps of 0 if the events occur before the start of the trace).

Can you please clarify what these entries mean?

**Comment by HaiyangDING** [comment]
The negative timestamps mean that the corresponding events happen before the start time of trace. We should have change them all to 0. Thanks for pointing this out, and I will fix the documentation.

Sorry for the inconvenience ...

**Comment by HaiyangDING** [comment]
Closing the issue.

**Comment by HaiyangDING** [comment]
Closing the issue.
