### ISSUE TITLE
Any plan for publishing job DAG information?

### ISSUE THREAD

**Issue by uchuhimo** [alibaba/clusterdata#3]
The scheduler may use DAG information in the job to achieve better resource utilization, which has been explored in [Graphene](https://www.usenix.org/system/files/conference/osdi16/osdi16-grandl-graphene.pdf). Publishing job DAG information will inspire further exploration to use DAG information in scheduling.

**Comment by furykerry** [comment]
We are working on it, but it may take some time. You can detail the information you need for DAG.

**Comment by uchuhimo** [comment]
The most critical DAG information is dependencies between tasks, which indicates the enforced schedule order of tasks. DAG information table may contain two fields: dependents and dependency type. For example, if both `a` and `c` depends on `b` with a many-to-one relationship (`b` has multiple instances, `a` has single instance, the instance of `a` depends on all instances of `b`), dependents of `b` is `a` and `c`, and dependency type is many-to-one, the corresponding row in DAG information CSV file is `b, a|c, many-to-one`.

**Comment by HaiyangDING** [comment]
DAG info is added in the v2018 trace. Enjoy :)

Closing the issue.
