### ISSUE TITLE
Adding LLC, Memory Bandwidth and Network Usage

### ISSUE THREAD

**Issue by buaa10061123** [alibaba/clusterdata#32]
The current data set only includes cpu, memory and disk usage data. I'm wondering if more kinds of resource usage data such as LLC, memory bandwidth and network can be provided. It's important for investigating how batch jobs influence online services on multidimensional resources. Many thanks.

**Comment by HaiyangDING** [comment]
Some of the mentioned metrics are added to the new trace while some are not.

Closing the issue and I will open another one for collecting feedbacks later.
