### ISSUE TITLE
cpu utilization vs linux cpu load

### ISSUE THREAD

**Issue by Pia-Narmadha** [alibaba/clusterdata#34]
what is the difference between cpu utilization vs linux cpu load average? These fields are present in machine usage table with the names as : util:CPU and load1: linux cpu load average of 1 minute

**Comment by HaiyangDING** [comment]
Hi,

In short, the CPU utilization means the how much time CPU is spending on calculation task(s) over some interval; while the CPU load average means how many tasks are waiting in the queue. 

You could refer to many articles for more details. Such as:

http://blog.scoutapp.com/articles/2009/07/31/understanding-load-averages
https://stackoverflow.com/questions/21617500/understanding-load-average-vs-cpu-usage

Good luck.

**Comment by HaiyangDING** [comment]
Closing the issue.
