### ISSUE TITLE
Server information

### ISSUE THREAD

**Issue by Pia-Narmadha** [alibaba/clusterdata#35]
1. In the server event table, we can see that all machines have 64 cpu's are they actual physical cores or virtual cpu's?
2. In the server event table, we can see that some machines have memory as 0.6. Is this is the free available memory and remaining memory was occupied by softwares?
3. Can you tell me the type of machine(like Dell power edge) used in the Alibaba server?

**Comment by HaiyangDING** [comment]
1. 64 CPUs are virtual CPUs, aka Hyper Thread to be more accurate.
2. It is the capacity of the server. However, this number is normalized.
3. Our servers are from various manufacturers.

I hope this answer helps. Good luck.

**Comment by HaiyangDING** [comment]
Closing the issue.
