### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by sure0000** [alibaba/clusterdata#4]
点击下载链接时为什么下载不了？还是用什么特定的方法下载？

**Comment by furykerry** [comment]
We use google form to host the questionaire, make sure you can access google service if you are in China

**Comment by iamzhout** [comment]
应该填写完调查表格就可以下载的，见下面的链接 (from [README.md](https://github.com/alibaba/clusterdata/blob/master/README.md))
> Downloading information can be found (after a short survey) in [this link](https://goo.gl/forms/eOoe6DwZQpd2H5n53)

**Comment by allencloud** [comment]
Do the ways provided by two above meet what you need? @sure0000 
If that, would you mind closing this issue? 🍻
