### ISSUE TITLE
About batch workload

### ISSUE THREAD

**Issue by odingzx** [alibaba/clusterdata#44]
1. The instance of batch workload is VMs, and may I ask what is the type of VM in alibaba cluster(kvm, xen or others)?
2. As mentioned in Papers using Alibaba cluster data, the resource management and job scheduling system of batch workload is Fuxi, and it can deal with different application(MapReduce, Spark etc), may I ask what is the type of applications in trace_201708? And I wonder what is the batch processing system mainly used in Alibaba Cluster?

**Comment by HaiyangDING** [comment]
1. An instance of batch workload is a "process" on the host.
2. Internally, we have various types of batch workloads and we use Fuxi and some other frameworks to manage them, while Fuxi is the largest for batch workloads.

**Comment by odingzx** [comment]
Thanks for your reply! To analyze the batch workloads, could I use the Implementation principles of Hadoop, Spark or one of batch processing systems?

**Comment by HaiyangDING** [comment]
I think so, but to be honest I am not sure I have fully understood your question ...

**Comment by odingzx** [comment]
OK, I think you have solved my questions, thanks a lot!

**Comment by Violet-Guo** [comment]
Closing the issue.
If I have missed something, please feel free to reopen this issue.

**Comment by Violet-Guo** [comment]
close

**Comment by Violet-Guo** [comment]
closes #44
