### ISSUE TITLE
why there are multiple records of one container_id in the  container_meta.csv? 

### ISSUE THREAD

**Issue by chenwenyan** [alibaba/clusterdata#47]

**Comment by jetmuffin** [comment]
It seems that a record shows the meta information at a specific time point. I found that some fields (`status`, `cpu_limit`) changed during the time period:

```
(containers.groupby("container_id").nunique())==1).all()

container_id     True
machine_id       True
time_stamp      False
app_du           True
status          False
cpu_request      True
cpu_limit       False
mem_size         True
dtype: bool
```

For example, container `c_10396` has stopped at relative timestamp `221530`,  so in later records the `status` field changed to `stopped`. And the same thing happened to container `c_22960` when its cpu limitation was changed to `480`.

```
      container_id machine_id  time_stamp    app_du   status  cpu_request  \
53844      c_10396     m_1986           0  app_4228  started          400   
53845      c_10396     m_1986      221530  app_4228  stopped          400   
53846      c_10396     m_1986      276497  app_4228  stopped          400   
53847      c_10396     m_1986      439454  app_4228  stopped          400   

       cpu_limit  mem_size  
53844        400      1.56  
53845        400      1.56  
53846        400      1.56  
53847        400      1.56  
```
```
       container_id machine_id  time_stamp    app_du   status  cpu_request  \
118899      c_22960     m_4024      663249  app_1596  started          400   
118900      c_22960     m_4024      672273  app_1596  started          400   

        cpu_limit  mem_size  
118899       4800      1.56  
118900        480      1.56  
```

Maybe we need to ping @HaiyangDING for more suggestions.

**Comment by HaiyangDING** [comment]
> It seems that a record shows the meta information at a specific time point. I found that some fields (`status`, `cpu_limit`) changed during the time period:
> 
> ```
> (containers.groupby("container_id").nunique())==1).all()
> 
> container_id     True
> machine_id       True
> time_stamp      False
> app_du           True
> status          False
> cpu_request      True
> cpu_limit       False
> mem_size         True
> dtype: bool
> ```
> For example, container `c_10396` has stopped at relative timestamp `221530`, so in later records the `status` field changed to `stopped`. And the same thing happened to container `c_22960` when its cpu limitation was configured to `480`.
> 
> ```
>       container_id machine_id  time_stamp    app_du   status  cpu_request  \
> 53844      c_10396     m_1986           0  app_4228  started          400   
> 53845      c_10396     m_1986      221530  app_4228  stopped          400   
> 53846      c_10396     m_1986      276497  app_4228  stopped          400   
> 53847      c_10396     m_1986      439454  app_4228  stopped          400   
> 
>        cpu_limit  mem_size  
> 53844        400      1.56  
> 53845        400      1.56  
> 53846        400      1.56  
> 53847        400      1.56  
> ```
> ```
>        container_id machine_id  time_stamp    app_du   status  cpu_request  \
> 118899      c_22960     m_4024      663249  app_1596  started          400   
> 118900      c_22960     m_4024      672273  app_1596  started          400   
> 
>         cpu_limit  mem_size  
> 118899       4800      1.56  
> 118900        480      1.56  
> ```
> Maybe we need to ping @HaiyangDING for more suggestions.

Hi, thanks for pointing this out. We may alter the `cpu_limit` for a small portion of containers at runtime. Here is one of such cases.

**Comment by chenwenyan** [comment]
Thanks a lot for your reply. Then I closing this issue.
