### ISSUE TITLE
Missing column in Trace_2018 machine_usage.csv

### ISSUE THREAD

**Issue by HongweiQin** [alibaba/clusterdata#48]
Hi Alibaba experts,
I notice that each record in the machine_usage.csv contains 9 colums. As shown below:
```
m_1932,388730,37,83,,,43.08,33.12,3
m_1932,388770,34,83,,,43.08,33.12,2
```
However, the trace_2018.md shows that there should be 10 columns.
Is there anything missing?
Thanks

**Comment by kennyzhangjun** [comment]
any ali experts

**Comment by HongweiQin** [comment]
Thank you for your help!

**Comment by yanzibugui** [comment]
发出来之前不检查一下吗？

**Comment by ying-zhang** [comment]
> 发出来之前不检查一下吗？

Take it easy and please behave yourself. 
Minor mistakes are inevitable, you see ...

**Comment by Violet-Guo** [comment]
Closing the issue.
If I have missed something, please feel free to reopen this issue.
