### ISSUE TITLE
very slow to download

### ISSUE THREAD

**Issue by lzhengchun** [alibaba/clusterdata#49]
it will take me 12 days to download (from US). Is there a better way to host the data? e.g., via DropBox?  of host a copy in US or so?

**Comment by HaiyangDING** [comment]
Hi, I will try to put a link more friend to US users.

**Comment by HaiyangDING** [comment]
Sorry for the delayed response and oversea-friendly downlinks (us-west) are provided now.

**Comment by chinmaya-dehury** [comment]
The links are not available for European user.

**Comment by karlhjm** [comment]
你好，邮件已收到。我处理完会马上给你回复，祝生活愉快！

**Comment by xuaikun** [comment]
您好，现在[alibaba_clusterdata_v2018](http://clusterdata2018pubcn.oss-cn-beijing.aliyuncs.com/alibaba_clusterdata2018.tar.gz)访问出错了，请问什么时候可以帮忙解决一下，感谢

**Comment by BBBeatrice** [comment]
您好，现在[alibaba_clusterdata_v2018](http://clusterdata2018pubcn.oss-cn-beijing.aliyuncs.com/alibaba_clusterdata2018.tar.gz)访问出错了，请问什么时候可以帮忙解决一下，感谢

**Comment by Yangkai6613** [comment]
您好我现在在国内也下载不了方便解决一下嘛

**Comment by reminderxxx** [comment]
你好我填写了survey似乎没有收到邮件或者 download link
