### ISSUE TITLE
About the batch_task.csv

### ISSUE THREAD

**Issue by allenbunny** [alibaba/clusterdata#5]
1. About the 2nd item in batch_task.csv:

Task table(batch_task.csv)

create_timestamp: the create time of a task
modify_timestamp: **latest state modification time**

in schema.csv:
![image](https://user-images.githubusercontent.com/7587514/30473724-dba78b80-9a33-11e7-9c13-8b698bf4528b.png)

So the 2nd is "latest state modification time" or "task end time"?

2. The task create time is timetamp. It seems longer than 24 hours.

**Comment by furykerry** [comment]
1. modify_timestamp  is the time of latest state modification. so modify_timestamp is the task end time if the task status is Terminated
2. i didn't notice any record with task create time span longer than 24 hours, can you provide a sample

thanks

**Comment by HaiyangDING** [comment]
Maybe we could close this issue? @allencloud

**Comment by HaiyangDING** [comment]
Closing the issue.
