### ISSUE TITLE
I cannot download the data and it shows“AccessDenied"

### ISSUE THREAD

**Issue by yayoyo66** [alibaba/clusterdata#57]
I open the v2018 download link and it shows the following information:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>
You have no right to access this object because of bucket acl.
</Message>
<RequestId>5C51C2AB307432057CAAF29B</RequestId>
<HostId>clusterdata2018pubcn.oss-cn-beijing.aliyuncs.com</HostId>
</Error>

**Comment by HelliotH** [comment]
Me too!It make me so upset!
