### ISSUE TITLE
Unit of "mem_size" in container_meta.csv

### ISSUE THREAD

**Issue by dcvan24** [alibaba/clusterdata#58]
The doc says `mem_size` is `Normalized to the largest memory size of all machines`, but the values are >1, while the normalized `plan_mem` in `batch_task.csv` is in [0, 1]. Are different normalization schemes used on the two datasets? Is it correct to assume the `mem_size` in `container_meta.csv` is the actual normalized value multiplied by 100? Thanks!

**Comment by HaiyangDING** [comment]
Hi, all `mem_size` are normalized between 0 and 100, including those in `batch_task.csv`, while those in `batch_task.csv` are in fact not very large which is why the records are all between [0, 1] after normalization.

**Comment by dcvan24** [comment]
@HaiyangDING Thanks a lot! This is very helpful!
