### ISSUE TITLE
How is the container CPU usage is calculated? 

### ISSUE THREAD

**Issue by ejalzahrani** [alibaba/clusterdata#62]
Hi All

Have a question regards to the container CPU usage “**cpu_util_precent:container_usage.csv**” 
How is this value calculated? 

I am a bit confusing about this value. For example, the machine “m_644” at timestamp “90080” hosts 7 containers:

container_id | machine_id | timestamp | cpu_utli_precent
-- | -- | -- | --
c_31920 | m_644 | 90080 | 13
c_5644 | m_644 | 90080 | 8
c_28792 | m_644 | 90080 | 7
c_21826 | m_644 | 90080 | 7
c_35230 | m_644 | 90080 | 7
c_58607 | m_644 | 90080 | 19
c_3 | m_644 | 90080 | 18

The total CPU usage for the containers at time 90080 is 79. While **cpu_util_precent:machine_usage.csv** at the same time “90080” is 42, So can anyone explain how is the calculation of “**cpu_util_precent: container_usage.csv**”? 

Thank you

**Comment by HaiyangDING** [comment]
Hi, the usage of a container is the percentage against the container's requested CPU number, not the machine CPU number.
