### ISSUE TITLE
machine_usage.csv文件中缺失的三列数据

### ISSUE THREAD

**Issue by uahappy** [alibaba/clusterdata#68]
machine_usage.csv文件中缺失了三列数据，和表的解释中对不上，可以麻烦你们告知一下machine_usage.csv文件中第五列以后每列对应的列名吗？不胜感激
![Snipaste_2019-05-28_18-01-00](https://user-images.githubusercontent.com/33249311/58471985-c522e300-8177-11e9-88bc-9c532b71d652.png)

**Comment by Violet-Guo** [comment]
> machine_usage.csv文件中缺失了三列数据，如下图
> ![image](https://user-images.githubusercontent.com/33249311/58469745-ae2dc200-8172-11e9-9c23-4b984f92c5d9.png)
> 和表的解释中对不上，可以麻烦你们告知一下machine_usage.csv文件中第五列以后每列对应的列名吗？不胜感激

https://github.com/alibaba/clusterdata/blob/master/cluster-trace-v2018/schema.txt
This file describes the schema of each data file. The missing columns are "mem_gps" and "mkpi".
If you import the dataset into the mysql or other database, you can see that is '\n'.

Hope this would help

**Comment by uahappy** [comment]
thank you.
