### ISSUE TITLE
Time reference and geographical info

### ISSUE THREAD

**Issue by Mema5** [alibaba/clusterdata#70]
Hi,
Thanks a lot for publishing these traces.
For my research, I would have liked to know the time reference of the data. Is time t=0 corresponding to midnight? I havn't found this information in the documentation.
Another question: is it possible to know the geographical location of the data center (or, at least, the area)?
Thank you for your answer,
Maël

**Comment by Violet-Guo** [comment]
Hi Mema5 ,
Sorry for the late response.

1. t=0 means 00:00 at the midnight.
2. I am sorry that the geographical location of the data center can not be published. All of these machines are from the same production cluster (means the same area).

Hope this would help :)

**Comment by Mema5** [comment]
Hi Violet-Guo, 
Thank you for your answer!
