### ISSUE TITLE
[Request] Add the online chat tool for better communication

### ISSUE THREAD

**Issue by gaocegege** [alibaba/clusterdata#8]
Now we have to create issues to ask questions about the data set, but some of them are not actual "issues", could we add gitter, slack or any other online chat tools for better communication?

**Comment by allencloud** [comment]
Thanks for your kind suggestion.

Currently, I am afraind we only have two kinds of communication way, one is github issues like you mentioned, and the other is the mailing list which is mentioned in README.md: alibaba-clusterdata@list.alibaba-inc.com.

At the very beginning, maybe many channels are not our plan A. To be honest, what we wish is effective and efficient communication. So we will try both two above ways for a period and see whether adding more ways is proper.

**Comment by gaocegege** [comment]
SGTM
