### ISSUE TITLE
Description of different states

### ISSUE THREAD

**Issue by lastweek** [alibaba/clusterdata#9]
Hi,
Is it possible to give a short description about the following instance status?
- Ready
- Waiting
- Running
- Terminated
- Failed
- Cancelled
- Interrupted

**Comment by furykerry** [comment]
OK， we will include the description in the next minor release of the cluster data, hopefully recently

**Comment by HaiyangDING** [comment]
@lastweek 

Sorry about the delay in response. Here is some explanation of the state machine:

* Task
    * Terminated: A task goes to ‘Terminated’ when all its instances are done
    * Waiting: A task in not initialized yet
    * Failed: Task fails
    * Running: The Task is being processed

* Instance
    * Terminated: An instance is done
    * Waiting: The instance can not run because some of its dependencies have not finished
    * Running: An Instance is ‘Running’ on a worker
    * Failed: An instance fails
    * Interrupted: It is feature we introduced for backup instance, the instance stops due to some reason

Hope this would help.

**Comment by lastweek** [comment]
@HaiyangDING 
Thanks a lot and Happy New Year!

**Comment by HaiyangDING** [comment]
The description of state machine of batch workload is added to documentation. Closing the issue.
